export enum routingUrl {
    login = 'login',
    loginFull = 'login',
    main = 'main',
    mainFull = 'main',
    personalArea = 'personalArea',
    personalAreaFull = 'main/personalArea',
    BankTransfer = 'BankTransfer',
    BankTransferFull = 'main/BankTransfer',
    RecentTranscations = 'RecentTranscations',
    RecentTranscationsFull = 'main/RecentTranscations',
    home = 'home',
    homeFull = 'main/home',
    admin = 'admin',
    adminFull = 'main/admin',
    bugList = 'bugList',
    bugListFull = 'main/admin/bugList',
    createAccount = 'createAccount',
    createAccountFull = 'main/admin/createAccount',
    updateAccount = 'updateAccount',
    updateAccountFull = 'main/admin/updateAccount',
    updateGroup = 'updateGroup',
    updateGroupFull = 'main/admin/updateGroup',
}